In [1]:
pwd

'D:\\GAISSA\\energy-repo\\last_repo\\energy-ml-serving\\experiments'

In [2]:
cd ..

D:\GAISSA\energy-repo\last_repo\energy-ml-serving

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [36]:
file_1 = "results/energibridge_example.csv"
df1 = pd.read_csv(file_1,)

file_2 = "results/gpu_results.csv"
df2 = pd.read_csv(file_2,)

In [37]:
df1.head()

,Time,CPU_FREQUENCY_0,CPU_FREQUENCY_1,CPU_FREQUENCY_2,CPU_FREQUENCY_3,CPU_FREQUENCY_4,CPU_FREQUENCY_5,CPU_FREQUENCY_6,CPU_FREQUENCY_7,CPU_USAGE_0,...,CPU_USAGE_6,CPU_USAGE_7,DRAM_ENERGY (J),PACKAGE_ENERGY (J),PP0_ENERGY (J),PP1_ENERGY (J),TOTAL_MEMORY,TOTAL_SWAP,USED_MEMORY,USED_SWAP
0,2024/04/30 19:06:23.773,2112,2112,2112,2112,2112,2112,2112,2112,18.218971,...,54.359402,1.075172,4428.836060,36189.687073,28878.376709,387.73761,17005068288,12348030976,13086830592,2029027328
1,2024/04/30 19:06:28.773,2112,2112,2112,2112,2112,2112,2112,2112,99.582047,...,100.000000,4.543594,4428.843262,36189.743286,28878.416626,387.73761,17005068288,12348030976,13086683136,2030555136
2,2024/04/30 19:06:33.773,2112,2112,2112,2112,2112,2112,2112,2112,12.057892,...,24.586769,1.412857,4428.995972,36192.827087,28881.175354,387.73761,17005068288,12348030976,13095006208,2044895232
3,2024/04/30 19:06:38.773,2112,2112,2112,2112,2112,2112,2112,2112,2.324516,...,2.024513,1.429489,4429.126953,36193.230408,28881.278503,387.73761,17005068288,12348030976,13095006208,2044895232
4,2024/04/30 19:06:43.773,2112,2112,2112,2112,2112,2112,2112,2112,3.775414,...,2.265457,2.967453,4429.266418,36193.605164,28881.451355,387.73761,17005068288,12348030976,13095088128,2044895232

In [38]:
df2.head()

,timestamp,name,utilization.gpu [%],utilization.memory [%],memory.total [MiB],memory.used [MiB],power.draw [W],power.max_limit [W],temperature.gpu
0,2024/04/30 19:06:21.773,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,183.90 W,350.00 W,58
1,2024/04/30 19:06:26.776,NVIDIA GeForce RTX 3090,48 %,24 %,24576 MiB,6084 MiB,188.06 W,350.00 W,56
2,2024/04/30 19:06:31.778,NVIDIA GeForce RTX 3090,35 %,15 %,24576 MiB,6084 MiB,197.91 W,350.00 W,58
3,2024/04/30 19:06:36.782,NVIDIA GeForce RTX 3090,11 %,10 %,24576 MiB,6084 MiB,189.22 W,350.00 W,55
4,2024/04/30 19:06:41.783,NVIDIA GeForce RTX 3090,21 %,9 %,24576 MiB,6084 MiB,193.54 W,350.00 W,58

In [39]:
name_mapping = {"DRAM_ENERGY (J)" : "dram_energy",
                "PACKAGE_ENERGY (J)":'package_energy',
               'PP0_ENERGY (J)':"pp0_energy",
               'PP1_ENERGY (J)':"pp1_energy"}
df1 = df1.rename(columns=name_mapping)
df1.columns = df1.columns.str.lower() # to lowcase
df1.columns

Index(['time', 'cpu_frequency_0', 'cpu_frequency_1', 'cpu_frequency_2',
       'cpu_frequency_3', 'cpu_frequency_4', 'cpu_frequency_5',
       'cpu_frequency_6', 'cpu_frequency_7', 'cpu_usage_0', 'cpu_usage_1',
       'cpu_usage_2', 'cpu_usage_3', 'cpu_usage_4', 'cpu_usage_5',
       'cpu_usage_6', 'cpu_usage_7', 'dram_energy', 'package_energy',
       'pp0_energy', 'pp1_energy', 'total_memory', 'total_swap', 'used_memory',
       'used_swap'],
      dtype='object')

In [40]:
df2.columns

Index(['timestamp', ' name', ' utilization.gpu [%]', ' utilization.memory [%]',
       ' memory.total [MiB]', ' memory.used [MiB]', ' power.draw [W]',
       ' power.max_limit [W]', ' temperature.gpu'],
      dtype='object')

In [41]:
name_mapping = { ' name': 'name',
                " utilization.gpu [%]" : "utilization_gpu",
                " utilization.memory [%]":'utilization_memory',
               ' memory.total [MiB]':"memory_total",
               ' memory.used [MiB]':"memory_used",
               ' power.draw [W]':'power_draw',
               ' power.max_limit [W]':"power_max_limit",
               ' temperature.gpu':"temperature_gpu",}
df2 = df2.rename(columns=name_mapping)
df2.columns = df2.columns.str.lower() # to lowcase
df2.columns

Index(['timestamp', 'name', 'utilization_gpu', 'utilization_memory',
       'memory_total', 'memory_used', 'power_draw', 'power_max_limit',
       'temperature_gpu'],
      dtype='object')

In [42]:
# Convert timestamps from string to datetime
df2['time'] = pd.to_datetime(df2['timestamp'])

# Assuming 'Time' in df2 needs to be converted or synchronized
# This might require more specific handling depending on the origin of these timestamps
# For example, converting UNIX time to datetime:
# df1['time'] = pd.to_datetime(df1['time'], unit='ms') 
df1['time'] = pd.to_datetime(df1['time'])

In [46]:
df3 = df1.copy()

In [49]:
# Add 4 minutes to each timestamp
df3['time'] += pd.Timedelta(minutes=4)

In [50]:
pwd

'D:\\GAISSA\\energy-repo\\last_repo\\energy-ml-serving'

In [52]:
df3.to_csv('results/energibridge_example2.csv', index=False)

In [ ]:
# Apply the condition to update the 'runtime' column
df.loc[(df['timestamp'] >= start_time) & (df['timestamp'] <= end_time), 'runtime'] = 'runtime1'

In [54]:
# Concatenate and sort
combined_df = pd.concat([df1, df2,df3], ignore_index=True)
combined_df = combined_df.sort_values(by='time')
combined_df

,time,cpu_frequency_0,cpu_frequency_1,cpu_frequency_2,cpu_frequency_3,cpu_frequency_4,cpu_frequency_5,cpu_frequency_6,cpu_frequency_7,cpu_usage_0,...,used_swap,timestamp,name,utilization_gpu,utilization_memory,memory_total,memory_used,power_draw,power_max_limit,temperature_gpu
16,2024-04-30 19:06:21.773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:06:21.773,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,183.90 W,350.00 W,58.0
0,2024-04-30 19:06:23.773,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,18.218971,...,2.029027e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024-04-30 19:06:26.776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:06:26.776,NVIDIA GeForce RTX 3090,48 %,24 %,24576 MiB,6084 MiB,188.06 W,350.00 W,56.0
1,2024-04-30 19:06:28.773,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,2112.0,99.582047,...,2.030555e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-04-30 19:06:31.778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:06:31.778,NVIDIA GeForce RTX 3090,35 %,15 %,24576 MiB,6084 MiB,197.91 W,350.00 W,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2024-04-30 19:14:36.969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:14:36.969,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,22.21 W,350.00 W,40.0
116,2024-04-30 19:14:41.971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:14:41.971,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,22.25 W,350.00 W,39.0
117,2024-04-30 19:14:46.972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:14:46.972,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,22.32 W,350.00 W,39.0
118,2024-04-30 19:14:51.974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:14:51.974,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,22.29 W,350.00 W,39.0
119,2024-04-30 19:14:56.976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2024/04/30 19:14:56.976,NVIDIA GeForce RTX 3090,0 %,0 %,24576 MiB,6084 MiB,22.33 W,350.00 W,38.0